
name: Task 1 YML File

on: 
    push:
        branches: ["main"]
    pull_request:
        branches: ["main"]
    
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest
            
        steps: 
            - uses: actions/checkout@v4

            - name: Print greeting
              run: echo Hola DevOps 🚀
            
            - name: show branch name
              run: |
                echo Github Ref: ${{github.ref}}
            
            - name: show username
              run: |
                echo Github Ref: ${{github.actor}}
            
            - name: Multiple lines
              run: |
                echo Preparing new build
                echo Build completed
            
            - name: create new file
              run: touch test.txt
    
    job:
        runs-on: ubuntu-latest
        needs: build
        steps:
            - name: show files
              run: echo ls -la
            
            - name: edit file test.txt
              run: echo testing new file > test.txt
    
    show-file:
        runs-on: ubuntu-latest
        needs: job
        steps:
            - name: show content
              run: cat test.text