
name: Task 1 YML File

on: 
    push:
        branches: ["main"]
    pull_request:
        branches: ["main"]
    
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest
            
        steps: 
            - uses: actions/checkout@v4

            - name: Print greeting
              run: echo Hola DevOps 🚀
            
            - name: show branch name
              run: |
                echo Github Ref: ${{github.ref}}
            
            - name: show username
              run: |
                echo Github Ref: ${{github.actor}}