name: Task 1 YML File

on: 
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest
        steps: 
        - name: Print greeting
          run: echo Hola DevOps 🚀

        - name: Create new file
          run: echo "Primer saludo" > test.txt

        - name: Upload file as artifact
          uses: actions/upload-artifact@v4
          with:
            name: test-file-step1
            path: test.txt

    job:
        runs-on: ubuntu-latest
        needs: build
        steps:
        - name: Download artifact
          uses: actions/download-artifact@v4
          with:
            name: test-file-step1

        - name: Show files
          run: ls -la

        - name: Edit file
          run: echo "Texto agregado en segundo job" >> test.txt

        - name: Upload updated file
          uses: actions/upload-artifact@v4
          with:
            name: test-file-step2
            path: test.txt

    show-file:
        runs-on: ubuntu-latest
        needs: job
        steps:
        - name: Download artifact
          uses: actions/download-artifact@v4
          with:
            name: test-file

        - name: Show content
          run: cat test.txt
