name: Test Self-Hosted Runner Test
on:
    push: 
        branches: ["main"]
    
    workflow_dispatch:
jobs:
  test:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - name: Print working dir
        run: pwd
      - name: Navigate Test folder
        run: cd Test
      
      - name: Show content
        run: run prueba.txt
