name: Test Self-Hosted Runner Test
on:
    push: 
        branches: ["main"]
    
    workflow_dispatch:
jobs:
  test:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4

      - name: Print working dir
        run: pwd

      - name: create Test file
        run: echo "new file" >> test.txt

      - name: Show content
        run: cat test.txt
